version: '3'
services:
    ubuntu:
        build:
            context: docker/build/
        volumes:
            - ./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/config/php-fpm/www.conf:/etc/php/7.2/fpm/pool.d/www.conf
            - ./docker/config/php-fpm/php.ini:/etc/php/7.2/fpm/conf.d/php.ini
            - ./docker/config/php-fpm/xdebug.ini:/etc/php/7.2/fpm/conf.d/xdebug.ini
            - ./docker/config/supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
            - ./docker/config/nginx/conf.d:/etc/nginx/conf.d
            - ./docker/config/home/www/.bashrc:/home/www/.bashrc
            - ./docker/config/home/www/history:/home/www/history
            - ./docker/server/nginx:/var/html/log
            - ./docker/server/supervisor:/var/log/supervisor
            - ./app:/var/www/html
        expose:
            - 80
        links:
        - mysql
        - firefox
        env_file:
        - ./docker/config/env/app.env
        environment:
            CLIENT_HOST: ${CLIENT_HOST}
        networks:
            self:
                ipv4_address: ${APP_URL}
    mysql:
        image: mysql:5.7.20
        environment:
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD_ROOT}
        volumes:
            - ./docker/server/mysql:/var/lib/mysql
            - ./docker/config/mysql/conf.d:/etc/mysql/conf.d
        networks:
            self:
                ipv4_address: ${DB_HOST}
    firefox:
        image: selenium/standalone-firefox:3.0
        volumes:
            - /dev/shm:/dev/shm
        ports:
            - "4444:4444"
        networks:
            self:
                ipv4_address: ${FIREFOX_HOST}
    node:
        image: node:10.13
        user: 1000:1000
        volumes:
        - ./app:/var/www/html
networks:
    self:
        driver: bridge
        ipam:
            config:
                - subnet: ${NETWORK_SUBNET}